name: Build Docker image

on:
  push:
    branches:
      - master

jobs:
  build-docker:
    runs-on: craci
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - run: docker build -t excalidraw .
